name: Get File Content on Windows

on:
  workflow_dispatch:

jobs:
  fetch-file:
    runs-on: windows-latest
    steps:
      - name: Get file content from GitHub using PowerShell
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: |
          $repo = "$env:GITHUB_REPOSITORY"
          $owner, $name = $repo.Split('/')
          $filePath = "test.txt"
          $branch = "main"

          $url = "https://api.github.com/repos/$owner/$name/contents/$filePath?ref=$branch"
          $headers = @{ Authorization = "Bearer $env:GITHUB_TOKEN"; "User-Agent" = "github-action" }

          $response = Invoke-RestMethod -Uri $url -Headers $headers
          $encodedContent = $response.content

          Write-Host "Encoded Content:"
          Write-Host $
