name: Create File from Laptop Content

on:
  push:
    branches:
      - main

jobs:
  create-file:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read content from local file
        run: |
          $content = Get-Content -Path "C:\D_drive\GCP\SSH\Powershell_ssh.txt"
          New-Item -Path new_directory\file.txt -ItemType File -Value $content

      - name: Commit and push changes
        run: |
          git config --global user.name "desh"
          git config --global user.email "desh.joshi@gmail.com"
          git add new_directory\file.txt
          git commit -m "Add file with content from laptop"
          git push
