name: Get File Content on Windows

on:
  workflow_dispatch:

jobs:
  fetch-file:
    runs-on: windows-latest
    steps:
      - name: Fetch file using PowerShell
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Debug: Print repo and branch
          Write-Host "GITHUB_REPOSITORY: $env:GITHUB_REPOSITORY"

          $repo = "$env:GITHUB_REPOSITORY"
          $owner, $name = $repo.Split('/')
          $filePath = "README.md"   # ✅ correct file name, relative to root
          $branch = "main"          # ✅ correct branch name

          $url = "https://api.github.com/repos/$owner/$name/contents/test.txt?ref=$branch"
          Write-Host "Calling URL: $url"

          $headers = @{
            Authorization = "Bearer $env:GITHUB_TOKEN"
            "User-Agent" = "github-action"
            Accept = "application/vnd.github.v3+json"
          }

          try {
            $response = Invoke-RestMethod -Uri $url -Headers $headers
            $encodedContent = $response.content
            $decodedBytes = [System.Convert]::FromBase64String($encodedContent)
            $decodedContent = [System.Text.Encoding]::UTF8.GetString($decodedBytes)

            Write-Host "`nDecoded Content:"
            Write-Host $decodedContent
          }
          catch {
            Write-Error "Failed to get file. Status Code: $($_.Exception.Response.StatusCode.Value__)"
            Write-Error $_
          }
